spring:
  application:
    name: clean-architecture-sdw-2024
  datasource:
    url: jdbc:h2:mem:ca2024
    driver-class-name: org.h2.Driver
    username: sa
    password: ''
  h2:
    console:
      enabled: true